name: Manuell deploy til dev gcp

on:
  workflow_dispatch:


permissions: {}

jobs:
  deploy_to_prod:
    name: Deploy to dev gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for push-image
    steps:
      -  uses: actions/checkout@v4
      -  uses: nais/deploy/actions/deploy@v2
         env:
           VAR: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/su-pdfgen:${{ github.sha }}
           CLUSTER: dev-gcp
           RESOURCE: nais.yml
