name: Manuell deploy

on:
  workflow_dispatch:
    inputs:
      deploy_prod:
        description: 'Deploy to production'
        type: boolean
        required: false
        default: false

permissions: {}

jobs:
  deploy_to_dev:
    name: Deploy to dev gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for push-image
    steps:
      -  uses: actions/checkout@v4
      -  uses: nais/deploy/actions/deploy@v2
         env:
           VAR: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/su-pdfgen:${{ github.sha }}
           CLUSTER: dev-gcp
           RESOURCE: nais.yml

  deploy_to_prod:
    name: Deploy to prod
    if: ${{ inputs.deploy_prod == true && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for push-image
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/su-pdfgen:${{ github.sha }}
          CLUSTER: prod-gcp
          RESOURCE: nais.yml